### ISSUE TITLE
jQuery(...).perfectScrollbar is not a function

### ISSUE THREAD

**Issue by bedo2991** [IceWreck/Argon-Dokuwiki-Template#32]
In the mobile view, the menu-expand icon does not work.
Dokuwiki: Release rc-2020-06-09 "Hogfather" RC3

**Comment by IceWreck** [comment]
We fixed it here but I didn't update the dokuwiki templates listing. To fix it you can install the template from this repo or wait and Ill update the listing tomorrow.

**Comment by IceWreck** [comment]
Done

**Comment by bedo2991** [comment]
Thanks, now the button works, but I still get the error in the console:
`-1 < navigator.platform.indexOf("Win") ? (jQuery(".wrapper .login-page, .register-page, .card").perfectScrollbar()`

**Comment by detoxhby** [comment]
++ currently affecting multiple deployments

Any possible workaround for this? (seems like the plugin is missing)

-----

There is the fix in upstream argon repo: https://github.com/creativetimofficial/argon-design-system/commit/5f9734af6aee0f637396285cf33e37ffc1bf9c28

**Comment by maroessler** [comment]
Does anyone have a fix for this? I tried looking at the upstream fix but I am not familiar with javascript, so I am not really knowing what I'm doing.

I'm having this issue using Argon together with the Drawio plugin.

**Comment by jacksitlab** [comment]
On my side this fix also hasn't worked I have removed the perfectscrollbar functionality enabled if windows detected

here my diff
```
diff --git a/public_html/lib/tpl/argon/assets/js/argon-design-system.min.js b/public_html/lib/tpl/argon/assets/js/argon-design-system.min.js
index 720b857..8b4da80 100644
--- a/public_html/lib/tpl/argon/assets/js/argon-design-system.min.js
+++ b/public_html/lib/tpl/argon/assets/js/argon-design-system.min.js
@@ -36,9 +36,7 @@ function debounce(t, o, r) {
             n = null, r || t.apply(e, a)
         }, o), r && !n && t.apply(e, a)
     }
-} - 1 < navigator.platform.indexOf("Win") ? (jQuery(".wrapper .login-page, .register-page, .card").perfectScrollbar(), 0 != jQuery(".tab-content .table-responsive").length && jQuery(".table-responsive").each(function () {
-    new PerfectScrollbar(jQuery(this)[0])
-}), $html.addClass("perfect-scrollbar-on")) : $html.addClass("perfect-scrollbar-off"), jQuery(document).ready(function () {
+} - 1 < $html.addClass("perfect-scrollbar-off"), jQuery(document).ready(function () {
     jQuery('[data-toggle="tooltip"], [rel="tooltip"]').tooltip(), jQuery('[data-toggle="popover"]').each(function () {
```

**Comment by Penworks** [comment]
Hi anyone following this issue. Im trying to figure out how to apply the fix that @jacksitlab has shared but I cant see his commit in the files and the downloaded files as they are atm in the repo dont seem to fix the issue. Any help appreciated.

UPDATE. (for the benefit of other readers.) After trying to implement the fix from @jacksitlab and not quite getting it I searched around for other ppl encountering errors with perfectScrollbar (even not with dokuwiki). I noted that the easiest fix is to stop initialising it. You can do this by removing it from script.js in the Argon tpl root folder. The script only throws errors in Windows, and without it, the gallery plugin works as it should in Windows. Not ideal, but a short term solution until I find a better plugin.
